package inventory_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/capybari-repo/capybari-core/analyzertest"
	"github.com/capybari-repo/capybari-core/builtin/inventory"
	"github.com/capybari-repo/capybari-core/facts"
)

func write(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for p, body := range files {
		full := filepath.Join(root, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

var fixture = map[string]string{
	"main.go":                      "package main\n\nfunc main() {}\n",
	"internal/x/x_test.go":         "package x\n",
	"api/gen.pb.go":                "// Code generated by protoc. DO NOT EDIT.\npackage api\n",
	"web/app.ts":                   "export const a = 1;\n",
	"web/app.spec.ts":              "it('x', () => {});\n",
	"README.md":                    "# demo\n",
	"Dockerfile":                   "FROM golang:1.22\n",
	".github/workflows/ci.yml":     "on: push\n",
	"infra/main.tf":                "resource \"x\" \"y\" {}\n",
	"go.mod":                       "module demo\n",
	"config/app.yaml":              "a: 1\n",
	"node_modules/lodash/index.js": "module.exports = {};\n",
	"static/logo.png":              "\x89PNG\x00\x00",
}

func TestInventoryWalk(t *testing.T) {
	root := t.TempDir()
	write(t, root, fixture)
	r, st := analyzertest.RunState(t, inventory.New(), analyzertest.Repo(t, root), analyzertest.Options{})
	var inv facts.Inventory
	if ok, err := st.Get(facts.KeyInventory, &inv); !ok || err != nil {
		t.Fatal("no inventory evidence")
	}
	if inv.Method != "walk" {
		t.Fatalf("method = %s", inv.Method)
	}
	kinds := map[string]facts.FileKind{}
	for _, f := range inv.Files {
		kinds[f.Path] = f.Kind
	}
	want := map[string]facts.FileKind{
		"main.go": facts.KindSource, "internal/x/x_test.go": facts.KindTest, "api/gen.pb.go": facts.KindGenerated,
		"web/app.ts": facts.KindSource, "web/app.spec.ts": facts.KindTest, "README.md": facts.KindDocs,
		"Dockerfile": facts.KindContainer, ".github/workflows/ci.yml": facts.KindCI, "infra/main.tf": facts.KindIaC,
		"go.mod": facts.KindBuild, "config/app.yaml": facts.KindConfig, "static/logo.png": facts.KindAsset,
	}
	for p, k := range want {
		if kinds[p] != k {
			t.Errorf("%s: kind %q, want %q", p, kinds[p], k)
		}
	}
	if _, ok := kinds["node_modules/lodash/index.js"]; ok {
		t.Error("node_modules must be excluded from a walk")
	}
	if len(inv.ExcludedDirs) != 1 || inv.ExcludedDirs[0] != "node_modules" {
		t.Errorf("excluded = %v", inv.ExcludedDirs)
	}
	if len(inv.Languages) == 0 || inv.Languages[0].Language != "Go" {
		t.Errorf("languages = %+v", inv.Languages)
	}
	// The public report fact must not carry the file list.
	var pub facts.Inventory
	if !r.Fact(facts.KeyInventory, &pub) || len(pub.Files) != 0 || pub.TotalFiles != inv.TotalFiles {
		t.Errorf("public fact: files=%d total=%d", len(pub.Files), pub.TotalFiles)
	}
}

func TestInventoryGit(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	root := t.TempDir()
	write(t, root, fixture)
	write(t, root, map[string]string{".gitignore": "config/\n"})
	for _, args := range [][]string{{"init", "-q"}, {"add", "-A", "-f", "node_modules"}, {"add", "-A"}} {
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %s", args, out)
		}
	}
	r, st := analyzertest.RunState(t, inventory.New(), analyzertest.Repo(t, root), analyzertest.Options{})
	var inv facts.Inventory
	st.Get(facts.KeyInventory, &inv)
	if inv.Method != "git-ls-files" {
		t.Fatalf("method = %s", inv.Method)
	}
	var sawIgnored, sawVendored bool
	for _, f := range inv.Files {
		if f.Path == "config/app.yaml" {
			sawIgnored = true
		}
		if f.Path == "node_modules/lodash/index.js" && f.Kind == facts.KindVendored {
			sawVendored = true
		}
	}
	if sawIgnored {
		t.Error(".gitignore'd file was inventoried")
	}
	if !sawVendored {
		t.Error("committed node_modules should be inventoried as vendored")
	}
	var hygiene bool
	for _, f := range r.Findings {
		if f.Rule != nil && f.Rule.ID == "committed-dependencies" {
			hygiene = true
		}
	}
	if !hygiene {
		t.Error("expected committed-dependencies finding")
	}
}
